name: Update Spatial Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 1 * *'
jobs:
  update:
    name: Update Spatial Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      - name: Update Route Data
        run: |
          npm run update-spatial

      - name: Commit and Push data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--no-verify'
          commit_message: Update Spatial data
          file_pattern: 'public/api/spatial/**'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
