name: Update Stop Name Data
on:
  workflow_dispatch:
    inputs:
      reRunId:
        description: 'Re-run Github Action ID'
        required: false
        type: number
  schedule:
    - cron: '0 16 * * 5'
jobs:
  update:
    name: Update Stop Name Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      - name: Update Stop Name Data
        run: |
          npm run update-stop-name

      # http://man7.org/linux/man-pages/man1/date.1.html
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Stop data
        uses: actions/cache/save@v3
        with:
          path: cache
          key: stop-data-${{ steps.get-date.outputs.date }}

      - name: Re-run Update Route
        if: inputs.reRunId != ''
        run: gh run rerun ${{ inputs.reRunId }}
