name: Update Route Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
jobs:
  update:
    name: Update Route Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # http://man7.org/linux/man-pages/man1/date.1.html
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Stop data
        uses: actions/cache/restore@v3
        with:
          path: cache
          key: stop-data-${{ steps.get-date.outputs.date }}
          restore-keys: stop-data

      - name: Install dependencies
        run: |
          npm install

      - name: Update Route Data
        run: |
          npm run update-route

      - name: Commit and Push data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--no-verify'
          commit_message: Update Route data
          file_pattern: 'public/api/route/**'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Echo env runUpdateStopName
        if: always()
        run: echo ${{ env.runUpdateStopName }}
        
      - name: Update Stop Name on exception
        if: failure() && env.runUpdateStopName == 'true'
        run: gh workflow run updateStopName.yml -f reRunId=$GITHUB_RUN_ID
