name: Update Route Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
jobs:
  update:
    name: Update Route Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Stop data
        id: cache-stop-data
        uses: actions/cache@v3
        with:
          path: cache
          key: stop-data

      - name: Install dependencies
        run: |
          npm install

      - name: Update Route Data
        run: |
          npm run update-route

      - name: Commit and Push data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--no-verify'
          commit_message: Update Route data
          file_pattern: 'public/api/route/**'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
